### ISSUE TITLE
how to export image model without embeding text-featrues?

### ISSUE THREAD

**Issue by xiguadong** [Ziad-Algrafi/yolo-world-onnx#1]
hello , could you tell me how to  export image model without embeding text-featrues? The onnx model export by the offcial repo caontains embeding.

**Comment by Ziad-Algrafi** [comment]
Hey there,
You could use ultralytics export method it will work cause it have
configuration for yolo world model check this video
https://youtu.be/kONm9nE5_Fk?si=M4YVpzmjm3onI-0E

Also use this code you need to install ultralytics first to do it

Pip install ultralytics

The code is below:

from ultralytics import YOLO

# Load a model
model = YOLO("yolov8n.pt")

# Export the model
model.export(format="onnx")


Also if you want to specify custom classes to be exported only which is
what you need when you don't want to use txt embedding feature
Do this

from ultralytics import YOLO

# Initialize a YOLO-World model
model = YOLO("yolov8s-world.pt") # or select yolov8m/l-world.pt

# Define custom classes
model.set_classes(["person", "bus"])

# Save the model with the defined offline vocabulary
model.save("custom_yolov8s.pt")


If you have any questions please let me know.
Good luck

**Comment by Ziad-Algrafi** [comment]
Hey there,

You could use Ultralytics' export method, it will work because it has a configuration for the YOLO-World model. Check out this video for more details:
https://youtu.be/kONm9nE5_Fk?si=M4YVpzmjm3onI-0E

First, install the Ultralytics package using:

pip install ultralytics

Here’s the code to export the model:

from ultralytics import YOLO

# Load a model
model = YOLO("yolov8n.pt")

# Export the model in ONNX format
model.export(format="onnx")

If you want to specify custom classes to be exported only (this is helpful when you don't want to use the text embedding feature), do this:

from ultralytics import YOLO

# Initialize a YOLO-World model
model = YOLO("yolov8s-world.pt")  # or yolov8m/l-world.pt

# Define custom classes
model.set_classes(["person", "bus"])

# Save the model with the defined custom vocabulary
model.save("custom_yolov8s.pt")

Let me know if you have any questions. Good luck!

**Comment by Ziad-Algrafi** [comment]
Hey there,

You can use Ultralytics' export method, which works with the YOLO-World model. For more details, check out [this video](https://youtu.be/kONm9nE5_Fk?si=M4YVpzmjm3onI-0E).

First, install the Ultralytics package:

```bash
pip install ultralytics
```

Here's the code to export the model:

```python
from ultralytics import YOLO

# Load a model
model = YOLO("yolov8n.pt")

# Export the model in ONNX format
model.export(format="onnx")
```
If you want to specify custom classes to be exported only (helpful when you don't want to use the text embedding feature), do this:

```python
from ultralytics import YOLO

# Initialize a YOLO-World model
model = YOLO("yolov8s-world.pt")  # or yolov8m/l-world.pt

# Define custom classes
model.set_classes(["person", "bus"])

# Save the model with the defined custom vocabulary
model.save("custom_yolov8s.pt")
```

Let me know if you have any questions. Good luck!
